version: "3.9"

services:
  linux-monitor:
    build: .
    container_name: linux-monitor
    restart: unless-stopped

    # подключаем .env
    env_file:
      - .env

    # монтируем лог на хост, чтобы не терялся
    volumes:
      - ./monitor.log:/app/monitor.log

    # запускаем мониторинг раз в минуту
    command: bash -lc 'while true; do /app/monitor.sh; sleep 60; done'
